spring.datasource.url=jdbc:postgresql://ep-autumn-scene-ama24l8d-pooler.c-5.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_UFsjZvJ2mk9r

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}